### ISSUE TITLE
Metrics not reported by dcgm-exporter

### ISSUE THREAD

**Issue by timrafay** [run-ai/fake-gpu-operator#93]
I have deployed the operator to a single node that is labeled properly and assigned the GPUs.  I have deployed the example workload on the node to consume the GPU.  The exporter is failing to send the utilization metrics and pod name.

Output from exporter showing the utilization at 0 and the missing namespace and pod details.

# HELP DCGM_FI_DEV_FB_FREE GPU Framebuffer Free
# TYPE DCGM_FI_DEV_FB_FREE gauge
DCGM_FI_DEV_FB_FREE{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-00b0279e-9a2e-56e3-90e2-52d8551d6031",container="",device="nvidia1",gpu="1",modelName="nvidia-A100",namespace="",pod=""} 11441
DCGM_FI_DEV_FB_FREE{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-bdf06b03-d5d7-5b41-932e-5fdd2ef59ddc",container="",device="nvidia3",gpu="3",modelName="nvidia-A100",namespace="",pod=""} 11441
DCGM_FI_DEV_FB_FREE{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-cc0557e3-8fbd-51f0-b7d3-7a548c581d7f",container="",device="nvidia0",gpu="0",modelName="nvidia-A100",namespace="",pod=""} 11441
DCGM_FI_DEV_FB_FREE{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-ef912753-2d5d-55ba-8ab5-dd7a82f54876",container="",device="nvidia2",gpu="2",modelName="nvidia-A100",namespace="",pod=""} 11441
# HELP DCGM_FI_DEV_FB_USED GPU Framebuffer Used
# TYPE DCGM_FI_DEV_FB_USED gauge
DCGM_FI_DEV_FB_USED{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-00b0279e-9a2e-56e3-90e2-52d8551d6031",container="",device="nvidia1",gpu="1",modelName="nvidia-A100",namespace="",pod=""} 0
DCGM_FI_DEV_FB_USED{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-bdf06b03-d5d7-5b41-932e-5fdd2ef59ddc",container="",device="nvidia3",gpu="3",modelName="nvidia-A100",namespace="",pod=""} 0
DCGM_FI_DEV_FB_USED{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-cc0557e3-8fbd-51f0-b7d3-7a548c581d7f",container="",device="nvidia0",gpu="0",modelName="nvidia-A100",namespace="",pod=""} 0
DCGM_FI_DEV_FB_USED{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-ef912753-2d5d-55ba-8ab5-dd7a82f54876",container="",device="nvidia2",gpu="2",modelName="nvidia-A100",namespace="",pod=""} 0
# HELP DCGM_FI_DEV_GPU_UTIL GPU Utilization
# TYPE DCGM_FI_DEV_GPU_UTIL gauge
DCGM_FI_DEV_GPU_UTIL{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-00b0279e-9a2e-56e3-90e2-52d8551d6031",container="",device="nvidia1",gpu="1",modelName="nvidia-A100",namespace="",pod=""} 0
DCGM_FI_DEV_GPU_UTIL{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-bdf06b03-d5d7-5b41-932e-5fdd2ef59ddc",container="",device="nvidia3",gpu="3",modelName="nvidia-A100",namespace="",pod=""} 0
DCGM_FI_DEV_GPU_UTIL{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-cc0557e3-8fbd-51f0-b7d3-7a548c581d7f",container="",device="nvidia0",gpu="0",modelName="nvidia-A100",namespace="",pod=""} 0
DCGM_FI_DEV_GPU_UTIL{Hostname="nvidia-dcgm-exporter-5e5b02",UUID="GPU-ef912753-2d5d-55ba-8ab5-dd7a82f54876",container="",device="nvidia2",gpu="2",modelName="nvidia-A100",namespace="",pod=""} 0
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary

Output from the status-updater:

`2024/09/26 15:39:57 StatusUpdater was Started
2024/09/26 15:39:57 Pruning topology ConfigMaps...
2024/09/26 15:39:57 Starting pod controller
2024/09/26 15:39:57 Starting node controller
2024/09/26 15:39:57 Handling node addition: tim-gpu-sim1
2024/09/26 15:39:57 Handling pod addition: sleepy-deployment-f54854f99-7c8gp
2024/09/26 15:39:57 Requested GPUs: 1
2024/09/26 15:39:57 GPU GPU-cc0557e3-8fbd-51f0-b7d3-7a548c581d7f is free, allocating...
2024/09/26 15:39:57 Error getting pod type for pod sleepy-deployment-f54854f99-7c8gp: pod sleepy-deployment-f54854f99-7c8gp has no constants.PodGroupNameAnnotation annotation
2024/09/26 15:39:57 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:39:57 Handling pod addition: sleepy-deployment-f54854f99-chsp4
2024/09/26 15:39:57 Requested GPUs: 1
2024/09/26 15:39:57 GPU GPU-cc0557e3-8fbd-51f0-b7d3-7a548c581d7f is free, allocating...
2024/09/26 15:39:57 Error getting pod type for pod sleepy-deployment-f54854f99-chsp4: pod sleepy-deployment-f54854f99-chsp4 has no constants.PodGroupNameAnnotation annotation
2024/09/26 15:39:57 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:40:24 Handling pod update: sleepy-deployment-f54854f99-7c8gp
2024/09/26 15:40:24 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:40:24 Handling pod update: sleepy-deployment-f54854f99-chsp4
2024/09/26 15:40:24 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:40:54 Handling pod update: sleepy-deployment-f54854f99-7c8gp
2024/09/26 15:40:54 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:40:54 Handling pod update: sleepy-deployment-f54854f99-chsp4
2024/09/26 15:40:54 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:40:54 Handling pod deletion: sleepy-deployment-f54854f99-7c8gp
2024/09/26 15:40:54 Failed to handle pod deletion: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:40:54 Handling pod deletion: sleepy-deployment-f54854f99-chsp4
2024/09/26 15:40:54 Failed to handle pod deletion: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:41:09 Handling pod addition: sleepy-deployment-d9769c574-lmzgz
2024/09/26 15:41:09 Requested GPUs: 1
2024/09/26 15:41:09 GPU GPU-cc0557e3-8fbd-51f0-b7d3-7a548c581d7f is free, allocating...
2024/09/26 15:41:09 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:41:09 Handling pod addition: sleepy-deployment-d9769c574-l8djr
2024/09/26 15:41:09 Requested GPUs: 1
2024/09/26 15:41:09 GPU GPU-cc0557e3-8fbd-51f0-b7d3-7a548c581d7f is free, allocating...
2024/09/26 15:41:09 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:41:09 Handling pod update: sleepy-deployment-d9769c574-lmzgz
2024/09/26 15:41:09 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:41:09 Handling pod update: sleepy-deployment-d9769c574-l8djr
2024/09/26 15:41:09 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:41:10 Handling pod update: sleepy-deployment-d9769c574-l8djr
2024/09/26 15:41:10 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:41:10 Handling pod update: sleepy-deployment-d9769c574-lmzgz
2024/09/26 15:41:10 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:41:11 Handling pod update: sleepy-deployment-d9769c574-lmzgz
2024/09/26 15:41:11 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 15:41:11 Handling pod update: sleepy-deployment-d9769c574-l8djr
2024/09/26 15:41:11 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 16:41:10 Handling pod update: sleepy-deployment-d9769c574-lmzgz
2024/09/26 16:41:10 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 16:41:10 Handling pod update: sleepy-deployment-d9769c574-l8djr
2024/09/26 16:41:10 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 16:41:11 Handling pod update: sleepy-deployment-d9769c574-l8djr
2024/09/26 16:41:11 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"
2024/09/26 16:41:11 Handling pod update: sleepy-deployment-d9769c574-lmzgz
2024/09/26 16:41:12 Failed to handle pod addition: configmaps "topology-tim-gpu-sim1" is forbidden: User "system:serviceaccount:gpu-operator-resources:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator-resources"`

I have attempted to use all of the possible MIG strategies, all having the same outcome of not reporting metrics.

**Comment by sachin-rafay** [comment]
I am facing the same problem

**Comment by pgodowski** [comment]
Have same problem, with eeors in status updater like:

```
2024/10/24 11:21:39 Failed to handle pod addition: configmaps "topology-worker0.fake-gpu.domain" is forbidden: User "system:serviceaccount:gpu-operator:status-updater" cannot patch resource "configmaps" in API group "" in the namespace "gpu-operator"
```

Manual fix is to edit `ClusterRole` `fake-status-updater` , adding `patch` verb for `ConfigMap` resource.

Will create PR for this.

However, status updated fails anyway, with error

```
2024/10/24 12:15:42 GPU GPU-63692fb7-614b-5f91-ad15-970ccdd4e01e is free, allocating...
2024/10/24 12:15:42 Failed to handle pod addition: PatchOptions.meta.k8s.io "" is invalid: fieldManager: Required value: is required for apply patch
2024/10/24 12:15:42 Handling pod update: gpu-test-5b7dc795b7-pdc2w
```
which seems the same symptom as https://github.com/kubernetes/client-go/issues/1036

 I am using Openshift 4.14 / k8s 1.27
